### PR TITLE
FIX added function exists around env declaration

### PR DESCRIPTION
**Pull request by bartjuh4**
Some other packages also using the env function and have their own declaration, this will cause a fatal error.

### CODE REVIEW

**Comment by oscarotero** [comment]
Hello.
This pull request includes some changes in the composer.json file like renamed the project and deleted the author :)
Anyway, this is the reason of why this package has the static method `Env::init()` to include the global function, so this should be fixed simply with this code:

``` php
if (!function_exists('env')) {
    Env::init();
}
```

In some cases including the `env()` is problematic (some libraries have their own `env()` function with a different purpose than this one, for example deployer), so you can use `Env::get()` instead.

**Comment by bartjuh4** [comment]
I'm sorry for the commits with changes in the composer.json. This was not intented.

**Comment by oscarotero** [comment]
I know, don't worry :smiley: 
I'm not sure whether is good idea to include the `function_exists` inside the `Env::init()` or not. Some alternatives:

``` php
//Create a specific function
Env::initIfNotExists();

//Or using an argument to check
Env::init(true);
```

**Comment by oscarotero** [comment]
Finally I've included the function_exists checking and `Env::init()` returns true or false if the function has been registered or not.
Thanks for reporting this.

**Pull request closed without merging**
